// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmojpcN4PQvDD8rmLsG9ZMaiVw-J4M7Zw',
    appId: '1:799749961987:web:cf32d5b8b02f8007979136',
    messagingSenderId: '799749961987',
    projectId: 'kutuphaneuygulamafo',
    authDomain: 'kutuphaneuygulamafo.firebaseapp.com',
    storageBucket: 'kutuphaneuygulamafo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtNlKNVn3mhwKDMRsvyniXZyaOdIjLEUI',
    appId: '1:799749961987:android:0de4cf36ecc4dc4e979136',
    messagingSenderId: '799749961987',
    projectId: 'kutuphaneuygulamafo',
    storageBucket: 'kutuphaneuygulamafo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc3n143qqKUeL64BFzWW5sV-wOTF5Mvpk',
    appId: '1:799749961987:ios:933040a6b6d18d6b979136',
    messagingSenderId: '799749961987',
    projectId: 'kutuphaneuygulamafo',
    storageBucket: 'kutuphaneuygulamafo.appspot.com',
    iosBundleId: 'com.example.kutuphaneUygulamaFo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc3n143qqKUeL64BFzWW5sV-wOTF5Mvpk',
    appId: '1:799749961987:ios:ae92bedd7b7919d4979136',
    messagingSenderId: '799749961987',
    projectId: 'kutuphaneuygulamafo',
    storageBucket: 'kutuphaneuygulamafo.appspot.com',
    iosBundleId: 'com.example.kutuphaneUygulamaFo.RunnerTests',
  );
}
